mybatis:
  type-aliases-package: com.wyu.partymanager.entity
mapper:
  mappers: com.wyu.partymanager.dao.IBaseDao
  identity: mysql
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://59.110.171.118/party?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: Liang45623+1628
    druid:
      initial-size: 5
      max-active: 30
      min-idle: 5
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 1 from dual
      test-while-idle: true
  redis:
    host: 127.0.0.1
    port: 6379
    password:
